services:
  postgres:
    image: postgres:16-alpine
    container_name: energy-postgres
    environment:
      POSTGRES_DB: energy
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
