spring:
  application:
    name: industrial-energy-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/energy
    username: energy
    password: energy

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
